// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/breadcrumb.ts";
import * as $$$1 from "./loaders/isMobile.ts";
import * as $$$2 from "./loaders/List/Sections.tsx";
import * as $$$3 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$4 from "./loaders/getGalleryMode.ts";
import * as $$$5 from "./loaders/matchUrl.ts";
import * as $$$$$$0 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$1 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Header/Header.tsx";
import * as $$$$$$5 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$6 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$7 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$8 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$9 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$10 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$11 from "./sections/Product/NotFound.tsx";
import * as $$$$$$12 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$13 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$14 from "./sections/Images/BrandsCarousel.tsx";
import * as $$$$$$15 from "./sections/Images/Carousel.tsx";
import * as $$$$$$16 from "./sections/Images/BannerText.tsx";
import * as $$$$$$17 from "./sections/Images/Instafeed.tsx";
import * as $$$$$$18 from "./sections/Images/BannerRow.tsx";
import * as $$$$$$19 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$20 from "./sections/Images/CarouselMatcher.tsx";
import * as $$$$$$21 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$22 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$23 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$24 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$25 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$26 from "./sections/Footer/Footer.tsx";
import * as $$$$$$27 from "./sections/Search/PLPTitle.tsx";
import * as $$$$$$28 from "./sections/Search/TextSEOMatcher.tsx";
import * as $$$$$$29 from "./sections/Search/TextSEO.tsx";
import * as $$$$$$30 from "./sections/Search/Breadcrumb.tsx";
import * as $$$$$$31 from "./sections/Layout/Grid.tsx";
import * as $$$$$$32 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$33 from "./sections/Layout/Container.tsx";
import * as $$$$$$34 from "./sections/Layout/Spacing.tsx";
import * as $$$$$$35 from "./sections/Layout/Flex.tsx";
import * as $$$$$$36 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$37 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$38 from "./sections/Gallery.tsx";
import * as $$$$$$39 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$40 from "./sections/Content/Articles.tsx";
import * as $$$$$$41 from "./sections/Content/Logos.tsx";
import * as $$$$$$42 from "./sections/Content/Benefits.tsx";
import * as $$$$$$43 from "./sections/Content/Text.tsx";
import * as $$$$$$44 from "./sections/Content/Faq.tsx";
import * as $$$$$$45 from "./sections/Theme/Theme.tsx";
import * as $$$$$$$$$0 from "./actions/newsletter/subscribe.ts";
import * as $$$$$$$$$1 from "./actions/gallery/mode.ts";
import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";

const manifest = {
  "loaders": {
    "deco-sites/sexshopatacadao/loaders/breadcrumb.ts": $$$0,
    "deco-sites/sexshopatacadao/loaders/getGalleryMode.ts": $$$4,
    "deco-sites/sexshopatacadao/loaders/isMobile.ts": $$$1,
    "deco-sites/sexshopatacadao/loaders/Layouts/ProductCard.tsx": $$$3,
    "deco-sites/sexshopatacadao/loaders/List/Sections.tsx": $$$2,
    "deco-sites/sexshopatacadao/loaders/matchUrl.ts": $$$5,
  },
  "sections": {
    "deco-sites/sexshopatacadao/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "deco-sites/sexshopatacadao/sections/Category/CategoryList.tsx": $$$$$$2,
    "deco-sites/sexshopatacadao/sections/Content/Articles.tsx": $$$$$$40,
    "deco-sites/sexshopatacadao/sections/Content/Benefits.tsx": $$$$$$42,
    "deco-sites/sexshopatacadao/sections/Content/Faq.tsx": $$$$$$44,
    "deco-sites/sexshopatacadao/sections/Content/Logos.tsx": $$$$$$41,
    "deco-sites/sexshopatacadao/sections/Content/Testimonials.tsx": $$$$$$39,
    "deco-sites/sexshopatacadao/sections/Content/Text.tsx": $$$$$$43,
    "deco-sites/sexshopatacadao/sections/Footer/Footer.tsx": $$$$$$26,
    "deco-sites/sexshopatacadao/sections/Gallery.tsx": $$$$$$38,
    "deco-sites/sexshopatacadao/sections/Header/Header.tsx": $$$$$$4,
    "deco-sites/sexshopatacadao/sections/Images/BannerGrid.tsx": $$$$$$21,
    "deco-sites/sexshopatacadao/sections/Images/BannerRow.tsx": $$$$$$18,
    "deco-sites/sexshopatacadao/sections/Images/BannerText.tsx": $$$$$$16,
    "deco-sites/sexshopatacadao/sections/Images/BrandsCarousel.tsx": $$$$$$14,
    "deco-sites/sexshopatacadao/sections/Images/Carousel.tsx": $$$$$$15,
    "deco-sites/sexshopatacadao/sections/Images/CarouselMatcher.tsx": $$$$$$20,
    "deco-sites/sexshopatacadao/sections/Images/ImageGallery.tsx": $$$$$$19,
    "deco-sites/sexshopatacadao/sections/Images/Instafeed.tsx": $$$$$$17,
    "deco-sites/sexshopatacadao/sections/Images/ShoppableBanner.tsx": $$$$$$22,
    "deco-sites/sexshopatacadao/sections/Layout/Container.tsx": $$$$$$33,
    "deco-sites/sexshopatacadao/sections/Layout/Flex.tsx": $$$$$$35,
    "deco-sites/sexshopatacadao/sections/Layout/Grid.tsx": $$$$$$31,
    "deco-sites/sexshopatacadao/sections/Layout/GridItem.tsx": $$$$$$32,
    "deco-sites/sexshopatacadao/sections/Layout/Spacing.tsx": $$$$$$34,
    "deco-sites/sexshopatacadao/sections/Links/LinkTree.tsx": $$$$$$23,
    "deco-sites/sexshopatacadao/sections/Links/Shortcuts.tsx": $$$$$$24,
    "deco-sites/sexshopatacadao/sections/Miscellaneous/CampaignTimer.tsx":
      $$$$$$1,
    "deco-sites/sexshopatacadao/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$0,
    "deco-sites/sexshopatacadao/sections/Newsletter/Newsletter.tsx": $$$$$$25,
    "deco-sites/sexshopatacadao/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$13,
    "deco-sites/sexshopatacadao/sections/Product/ImageGallerySlider.tsx":
      $$$$$$6,
    "deco-sites/sexshopatacadao/sections/Product/NotFound.tsx": $$$$$$11,
    "deco-sites/sexshopatacadao/sections/Product/NotFoundChallenge.tsx":
      $$$$$$5,
    "deco-sites/sexshopatacadao/sections/Product/ProductInfo.tsx": $$$$$$10,
    "deco-sites/sexshopatacadao/sections/Product/ProductShelf.tsx": $$$$$$8,
    "deco-sites/sexshopatacadao/sections/Product/ProductShelfTabbed.tsx":
      $$$$$$9,
    "deco-sites/sexshopatacadao/sections/Product/SearchResult.tsx": $$$$$$12,
    "deco-sites/sexshopatacadao/sections/Product/Wishlist.tsx": $$$$$$7,
    "deco-sites/sexshopatacadao/sections/Search/Breadcrumb.tsx": $$$$$$30,
    "deco-sites/sexshopatacadao/sections/Search/PLPTitle.tsx": $$$$$$27,
    "deco-sites/sexshopatacadao/sections/Search/TextSEO.tsx": $$$$$$29,
    "deco-sites/sexshopatacadao/sections/Search/TextSEOMatcher.tsx": $$$$$$28,
    "deco-sites/sexshopatacadao/sections/Social/InstagramPosts.tsx": $$$$$$36,
    "deco-sites/sexshopatacadao/sections/Social/WhatsApp.tsx": $$$$$$37,
    "deco-sites/sexshopatacadao/sections/Theme/Theme.tsx": $$$$$$45,
  },
  "actions": {
    "deco-sites/sexshopatacadao/actions/gallery/mode.ts": $$$$$$$$$1,
    "deco-sites/sexshopatacadao/actions/newsletter/subscribe.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/sexshopatacadao/apps/decohub.ts": $$$$$$$$$$$1,
    "deco-sites/sexshopatacadao/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/sexshopatacadao",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
